# Generated by Django 6.0.3 on 2026-03-07 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='network',
        ),
        migrations.AddField(
            model_name='electronicsnetwork',
            name='products',
            field=models.ManyToManyField(blank=True, to='network.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='electronicsnetwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='electronicsnetwork',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Задолженность перед поставщиком (₽)'),
        ),
        migrations.AlterField(
            model_name='electronicsnetwork',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], help_text='Определяется автоматически через поставщика', verbose_name='Уровень иерархии'),
        ),
    ]
